### ISSUE TITLE
大佬，骚包和ptt一直报错可否更新一下

### ISSUE THREAD

**Issue by 522654518** [htnanako/movie-robot-public#1]
ptt报错--------------------
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: torrent_info.download_url
[SQL: INSERT INTO torrent_info (gmt_create, id, site_id, gmt_modified, name, subject, cate_level1, cate_id, details_url, download_url, imdb_id, publish_date, size_mb, upload_count, downloading_count, download_count, free_deadline, download_volume_factor, upload_volume_factor, minimum_ratio, minimum_seed_time, poster_url) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2022-09-21 06:16:13', 34405, 'pttime', '2022-09-21 06:16:13', '京东PT圈相关产品 -- 2022-09-20 晚间更新', '测试阶段 - 如果有意见或建议请在帖子下评论 | 希望没打扰到你 | 感谢已经下单的站友', None, '500', 'https://www.pttime.org/details.php?id=34405&hit=1', None, None, '2022-09-20 10:54:37', 0.0, 0, 0, 0, '', 1.0, 1, 0.0, 0, '')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
---------------------------------------------
貌似是因为是广告所以缺少参数，这个广告应该怎么屏蔽呢
----------------------------------------
骚包报错更加频繁
2022/09/21 06:14:48 - ThreadPoolExecutor-5_7 - ERROR: date解析出错 values: {'id': '36189', 'category': '404', 'title_default': 'Foo Fighters Sonic Highways S01 1080p BluRay Remux AVC TrueHD 5.1-HDS', 'title_optional': 'Foo Fighters Sonic Highways S01 1080p BluRay Remux AVC TrueHD 5.1-HDS', 'title': 'Foo Fighters Sonic Highways S01 1080p BluRay Remux AVC TrueHD 5.1-HDS', 'details': 'details.php?id=36189&hit=1', 'download': 'download.php?id=36189&passkey=b4285770fed8ecc5423e51be0c2581ca', 'size': '9时59分', 'grabs': '5', 'seeders': '66.39GB', 'leechers': '1', 'date_elapsed': None, 'date_added': '0'} tag: <tr class="torrent_table" id="tid_36189"><td class="rowfollow nowrap" id="torrents_td" style="padding: 0px" valign="middle"><a href="torrents.php?cat=404"><img alt="纪录片" class="c_doc" src="pic/cattrans.gif" style="background-image: url(pic/category/CHD/scenetorrents/chs/doc.png); height:60px; width:48px" title="纪录片"/></a><a href="torrents.php?cat=404&amp;source=41"><img alt="纪录片-其他" src="pic/cattrans.gif" style="width:48px;height:60px;background-image: url(pic/category/CHD/scenetorrents/chs//sec/41.png);background-position: top left;" title="纪录片-其他"/></a></td><td align="left" class="rowfollow" id="torrents_td" width="100%"><table class="torrentname" style="background-color:transparent" width="100%"><td class="embedded"><span class="browse new">新</span><a href="details.php?id=36189&amp;hit=1" title="Foo Fighters Sonic Highways S01 1080p BluRay Remux AVC TrueHD 5.1-HDS"><b>Foo Fighters Sonic Highways S01 1080p BluRay Remux AVC TrueHD 5.1-HDS</b></a><font color="#888888"> <img alt="Free" class="pro_free" src="pic/trans.gif" title="Free"/> <b>[剩余时间：<span title="2022-09-21 20:15:04">14时0分</span>]</b></font><br/>索尼克高速公路 第一季</td><td class="embedded" style="text-align: right; " valign="middle" width="80"> <a href="download.php?id=36189&amp;passkey=b4285770fed8ecc5423e51be0c2581ca"><img alt="download" class="download" src="pic/trans.gif" style="padding-bottom: 2px;" title="下载本种"/></a> <a href="javascript: bookmark(36189,48,1);" id="bookmark48"><img alt="Unbookmarked" class="delbookmark" src="pic/trans.gif" title="收藏"/></a> <a href="javascript: truckmark(36189,48,1);" id="truckmark48"><img alt="Untruckmarked" class="truckmark" src="pic/trans.gif" title="放进小货车"/></a><br/> <span></span> <a href="details.php?id=36189&amp;hit=1"><img src="styles/img/imdb.gif" style="vertical-align: text-bottom;" title="IMDb评分：8.7"/> <span style="vertical-align: text-bottom;">8.7</span></a></td></table></td><td class="rowfollow nowrap" id="torrents_td"><a href="faq.php"><font color="a70000">15时</font></a></td><td class="rowfollow" id="torrents_td">8</td><td class="rowfollow" id="torrents_td"><a href="comment.php?action=add&amp;pid=36189&amp;type=torrent" title="添加评论">0</a></td><td class="rowfollow nowrap" id="torrents_td"><span title="2022-09-20 20:15:04">9时<br/>59分</span></td><td class="rowfollow" id="torrents_td">66.39<br/>GB</td><td class="rowfollow" id="torrents_td"><b><a href="details.php?id=36189&amp;hit=1&amp;dllist=1#seeders">1</a></b></td><td class="rowfollow" id="torrents_td"><b><a href="details.php?id=36189&amp;hit=1&amp;dllist=1#leechers">5</a></b></td><td class="rowfollow" id="torrents_td">0</td><td class="rowfollow" id="torrents_td"><i>匿名</i></td></tr>
Traceback (most recent call last):
  File "mbot/site/htmlparser.py", line 193, in mbot.site.htmlparser.HtmlParser.parse_item_fields
  File "mbot/site/htmlparser.py", line 156, in mbot.site.htmlparser.HtmlParser.__filter_value__
  File "mbot/site/htmlparser.py", line 84, in mbot.site.htmlparser.filter_dateparse
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '0' does not match format '%Y-%m-%d %H:%M:%S'
2022/09/21 06:14:48 - ThreadPoolExecutor-5_7 - ERROR: date解析出错 values: {'id': '36188', 'category': '401', 'title_default': 'Shang-Chi and the Legend of the Ten Rings 2021 1080p 3D BluRay AVC TrueHD 7.1 Atmos...', 'title_optional': 'Shang-Chi and the Legend of the Ten Rings 2021 1080p 3D BluRay AVC TrueHD 7.1 Atmos-ZMAN', 'title': 'Shang-Chi and the Legend of the Ten Rings 2021 1080p 3D BluRay AVC TrueHD 7.1 Atmos-ZMAN', 'details': 'details.php?id=36188&hit=1', 'download': 'download.php?id=36188&passkey=b4285770fed8ecc5423e51be0c2581ca', 'size': '10时1分', 'grabs': '0', 'seeders': '44.86GB', 'leechers': '3', 'date_elapsed': None, 'date_added': '0'} tag: <tr class="torrent_table" id="tid_36188"><td class="rowfollow nowrap" id="torrents_td" style="padding: 0px" valign="middle"><a href="torrents.php?cat=401"><img alt="电影" class="c_movies" src="pic/cattrans.gif" style="background-image: url(pic/category/CHD/scenetorrents/chs/movies_dvdr.png); height:60px; width:48px" title="电影"/></a><a href="torrents.php?cat=401&amp;source=55"><img alt="电影-原盘" src="pic/cattrans.gif" style="width:48px;height:60px;background-image: url(pic/category/CHD/scenetorrents/chs//sec/55.png);background-position: top left;" title="电影-原盘"/></a></td><td align="left" class="rowfollow" id="torrents_td" width="100%"><table class="torrentname" style="background-color:transparent" width="100%"><td class="embedded"><span class="browse new">新</span><span class="tag yp" data-tag="yp"> 原盘 </span> <a href="details.php?id=36188&amp;hit=1" title="Shang-Chi and the Legend of the Ten Rings 2021 1080p 3D BluRay AVC TrueHD 7.1 Atmos-ZMAN"><b>Shang-Chi and the Legend of the Ten Rings 2021 1080p 3D BluRay AVC TrueHD 7.1 Atmos...</b></a><font color="#888888"> <img alt="Free" class="pro_free" src="pic/trans.gif" title="Free"/> <b>[剩余时间：<span title="2022-09-21 20:12:38">13时58分</span>]</b></font><br/>尚气与十环传奇 / 尚气与十环帮传奇(港) / 尚气与十戒传奇 / 尚气 3D原盘</td><td class="embedded" style="text-align: right; " valign="middle" width="80"> <a href="download.php?id=36188&amp;passkey=b4285770fed8ecc5423e51be0c2581ca"><img alt="download" class="download" src="pic/trans.gif" style="padding-bottom: 2px;" title="下载本种"/></a> <a href="javascript: bookmark(36188,49,1);" id="bookmark49"><img alt="Unbookmarked" class="delbookmark" src="pic/trans.gif" title="收藏"/></a> <a href="javascript: truckmark(36188,49,1);" id="truckmark49"><img alt="Untruckmarked" class="truckmark" src="pic/trans.gif" title="放进小货车"/></a><br/> <span></span> <a href="details.php?id=36188&amp;hit=1"><img src="styles/img/imdb.gif" style="vertical-align: text-bottom;" title="IMDb评分：7.4"/> <span style="vertical-align: text-bottom;">7.4</span></a></td></table></td><td class="rowfollow nowrap" id="torrents_td"><a href="faq.php"><font color="a50000">14时</font></a></td><td class="rowfollow" id="torrents_td">1</td><td class="rowfollow" id="torrents_td"><a href="comment.php?action=add&amp;pid=36188&amp;type=torrent" title="添加评论">0</a></td><td class="rowfollow nowrap" id="torrents_td"><span title="2022-09-20 20:12:38">10时<br/>1分</span></td><td class="rowfollow" id="torrents_td">44.86<br/>GB</td><td class="rowfollow" id="torrents_td"><b><a href="details.php?id=36188&amp;hit=1&amp;dllist=1#seeders">3</a></b></td><td class="rowfollow" id="torrents_td">0</td><td class="rowfollow" id="torrents_td"><a href="viewsnatches.php?id=36188"><b>27</b></a></td><td class="rowfollow" id="torrents_td"><i>匿名</i></td></tr>
Traceback (most recent call last):
  File "mbot/site/htmlparser.py", line 193, in mbot.site.htmlparser.HtmlParser.parse_item_fields
  File "mbot/site/htmlparser.py", line 156, in mbot.site.htmlparser.HtmlParser.__filter_value__
  File "mbot/site/htmlparser.py", line 84, in mbot.site.htmlparser.filter_dateparse
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '0' does not match format '%Y-%m-%d %H:%M:%S'

----------------------------------------------

**Comment by htnanako** [comment]
烧包没问题。ptt删了。

**Comment by 522654518** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
