### ISSUE TITLE
大佬 请问这个site要怎么制作呀有什么规律嘛

### ISSUE THREAD

**Issue by Jie-su** [htnanako/movie-robot-public#12]
hdvideo这个站好像看到没人做 想做一个 但是看了几个模版没看出来要按什么思路来

**Comment by htnanako** [comment]
> hdvideo这个站好像看到没人做 想做一个 但是看了几个模版没看出来要按什么思路来

css选择器

**Comment by htnanako** [comment]
> hdvideo这个站好像看到没人做 想做一个 但是看了几个模版没看出来要按什么思路来

css selector

**Comment by kiddyyang** [comment]
尝试用ChatGPT参考大佬的rarbg站点文件，仿照写一个脚本去爬1337x等公开站点，发现html文件的内容差异太大了。
大佬能否大概给点思路？

感觉MB对于我这样的非PT玩家门槛还是太高了，要是能像老版本Nas-tools那样支持Jackett就好了。
我理解这里面肯定存在共享精神的原因，但现在PT站点的门槛本身又非常高，新人真不知道能何去何从。

**Comment by htnanako** [comment]
> 

就是css selector 每个值找到对应的页面元素 让程序能爬到就行了

**Comment by Renneking** [comment]
大佬能不能做个https://share.dmhy.org/的规则啊 ACG被墙了 没有规则下动漫了

**Comment by htnanako** [comment]
> 大佬能不能做个https://share.dmhy.org/的规则啊 ACG被墙了 没有规则下动漫了

动漫去观众下挺好的。bt站看蜜柑的文件模仿。
