### ISSUE TITLE
编写配置求助

### ISSUE THREAD

**Issue by 0xWelt** [htnanako/movie-robot-public#13]
大佬您好，我在尝试编写freefarm和byrpt的配置文件，想弄好了给您的public sites提交PR。现在获取用户信息和订阅下载都没啥问题，但是自动刷流好像一直没成功，想请教一下大佬看看能否提供些帮助

**Comment by 0xWelt** [comment]
还有就是想问问这个配置的语法有手册吗？现在只能依葫芦画瓢，拿不同sites里出现过的拼凑

**Comment by htnanako** [comment]
没号 语法学css selector
