### ISSUE TITLE
馒头配置出现BUG

### ISSUE THREAD

**Issue by WuhanSy** [htnanako/movie-robot-public#18]
在MR中搜索动画片时，没有馒头的搜索结果，比如小猪佩奇，馒头网有许多资源，但是在MR中无法搜索到。有可能是馒头的标签分类变更导致，请大佬及时维护。感谢！

**Comment by htnanako** [comment]
> 在MR中搜索动画片时，没有馒头的搜索结果，比如小猪佩奇，馒头网有许多资源，但是在MR中无法搜索到。有可能是馒头的标签分类变更导致，请大佬及时维护。感谢！

我这没有问题。查你自己的问题。

**Comment by WuhanSy** [comment]
自身问题，cookie过期和缓存导致，感谢回复。
