### ISSUE TITLE
请求大佬适配一个很多资源的站点

### ISSUE THREAD

**Issue by androiddisk** [htnanako/movie-robot-public#3]
https://sukebei.nyaa.si/

 这个站点不需要账号直接就能下载。 希望能加进去 感谢

**Comment by htnanako** [comment]
> https://sukebei.nyaa.si/
> 
> 这个站点不需要账号直接就能下载。 希望能加进去 感谢

有人写了pr了，已合并。

**Comment by androiddisk** [comment]
谢谢
