### ISSUE TITLE
求大佬增加朱雀的配置，谢谢

### ISSUE THREAD

**Issue by ceozero** [htnanako/movie-robot-public#7]
站点朱雀 https://zhuque.in/index
进不了站的可以留邮箱我发腰子。

**Comment by sexyfeifan** [comment]
zhoufeifan@gmail.com

**Comment by ceozero** [comment]
> [zhoufeifan@gmail.com](mailto:zhoufeifan@gmail.com)

发了腰子，谢谢适配。

**Comment by sexyfeifan** [comment]
收到谢谢大佬🫡

**Comment by htnanako** [comment]
做不了。朱雀的登录认证不只是cookie。
